Initial commit
ishoborabyose/medical-core pull request #1
Opened 2022-09-30 08:57 UTC by ishoborabyose

What does this PR do?
This is for a page created using BEM

Description of Task to be completed?
files that hold or contain HTML, CSS, and images. 

How should this be manually tested?
After forking, this repository, clone it cd into and run the live server

2022-10-01 21:48 UTC, IbrahimBagalwa requested changes
## Request Change
keep it up:)
implement the change and re-request the review again. thank you

2022-10-01 21:48 UTC, IbrahimBagalwa commented on index.html
> +    <div class="medical-header__container">
## bem naming wrong
this is not bem `medical-header__container`. here you are using element without its block. follow this link [here](https://getbem.com/naming/) for more detail

2022-10-01 21:48 UTC, IbrahimBagalwa commented on index.html
> +                <li class="medical-header__item--signup"><a class="medical-header__anchor--signup" href="">Join Us</a></li>
## bem naming wrong
`medical-header__item--login` , `medical-header__item--signup`, `medical-header__anchor--login` and `medical-header__anchor--signup` this is not bem you are using modifier without its element or block. follow the naming bem link [here](https://getbem.com/naming/).

2022-10-01 21:48 UTC, IbrahimBagalwa commented on index.html
> +            <p class="medical-banner__paragraph--2">Get your best looking smile now!</p>
`medical-banner__paragraph--1` `medical-banner__paragraph--2` find a explicite name for your modifier and you are using the modifier without its block or element. this is not bem

2022-10-01 21:48 UTC, IbrahimBagalwa commented on index.html
> +                <li class="medical-banner__list__item medical-banner__list__item--learn">Learn More</li>
`medical-banner__list__item` `medical-banner__list__item--join` `medical-banner__list__item--join` `medical-banner__list__item--learn` this is not bem. it was a old way of naming nested element. follow this link [here](https://scalablecss.com/bem-nesting-grandchild-elements/)

2022-10-01 21:48 UTC, IbrahimBagalwa commented on index.html
> +        <p class="team-paragraph">Problems trying to resolve the conflict between
here you are making `team-title` `team-subtitle` `team-paragraph` you put them as a block but I don't see where you are using them

2022-10-01 21:48 UTC, IbrahimBagalwa commented on index.html
> +                    </div>
tags without class name is not bem. try to find the classname for your `img`

2022-10-01 21:48 UTC, IbrahimBagalwa commented on style.css
> +  body {
find a class name for this `body`

2022-10-01 21:48 UTC, IbrahimBagalwa commented on style.css
> +.medical-header__logo .medical-header__anchor{
this is not bem you try to repete your self here `.medical-header__logo .medical-header__anchor`.

2022-10-01 21:48 UTC, IbrahimBagalwa commented on style.css
> +.medical-header__list .medical-header__item{
here as well

2022-10-01 21:48 UTC, IbrahimBagalwa commented on style.css
> +.medical-header__list .medical-header__item .medical-header__anchor{
even here `.medical-header__list .medical-header__item .medical-header__anchor`

2022-10-01 21:48 UTC, IbrahimBagalwa commented on style.css
> +.medical-header__list .medical-header__item--login{
here as well

2022-10-01 21:48 UTC, IbrahimBagalwa commented on style.css
> +.medical-header__list .medical-header__item--login  .medical-header__anchor--login {
even here

2022-10-01 21:48 UTC, IbrahimBagalwa commented on style.css
> +    .medical-header__list .medical-header__item--signup{
even here

2022-10-01 21:48 UTC, IbrahimBagalwa commented on style.css
> +    .medical-header__list .medical-header__item--signup::after{
here as well

2022-10-01 21:48 UTC, IbrahimBagalwa commented on style.css
> +    .medical-header__list  .medical-header__anchor--signup {
even here

2022-10-01 21:48 UTC, IbrahimBagalwa commented on style.css
> +.medical-banner__list .medical-banner__list__item{
chnge here as well

2022-10-01 21:48 UTC, IbrahimBagalwa commented on style.css
> +.medical-expert__img-wrapper, .medical-expert__body {
even here

2022-10-02 00:22 UTC, mbukeRepo commented on index.html
> +    <div class="medical-header__container">
Like Ibrahim said `medical-header__container` should have a parent block called `medical-header`

2022-10-02 01:32 UTC, mbukeRepo reviewed
Congs :clap: :
but please implement these changes

2022-10-02 01:32 UTC, mbukeRepo commented on index.html
> +                        <img class="social-icon" src="./assets/facebook (1).svg" alt="">
`social-icon` is an element of `social` so use `social__icon`

2022-10-02 01:32 UTC, mbukeRepo commented on index.html
> +                        <img class="social-icon" src="./assets/instagram (1).svg" alt="">
same here

2022-10-02 01:32 UTC, mbukeRepo commented on index.html
> +    <div class="medical-header__container">
`medical-header__container` is an element without a parent block `medical-header`

2022-10-02 01:32 UTC, mbukeRepo commented on index.html
> +    <div class="medical-header__container">
a block comes before an element

2022-10-02 07:28 UTC, ishoborabyose commented
thank you for your feedback.

On Sun, Oct 2, 2022 at 3:32 AM mbuke_repo ***@***.***> wrote:

> ***@***.**** commented on this pull request.
>
> Congs 👏 :
> but please implement these changes
> ------------------------------
>
> In index.html
> <https://github.com/ishoborabyose/medical-core/pull/1#discussion_r985164242>
> :
>
> > +        <p class="team-subtitle">Our Team</p>
>
> +        <p class="team-paragraph">Problems trying to resolve the conflict between
>
> +            the two major realms of Classical physics: Newtonian mechanics </p>
>
> +
>
> +
>
> +
>
> +            <div class="team-card-container">
>
> +                <div class="team-card">
>
> +                    <img class="team-card__img" src="./assets/image-doctor-3.png" alt="">
>
> +
>
> +                        <p class="team-card__title">Julian Jameson</p>
>
> +                        <p class="team-card__subtitle"> proffession </p>
>
> +
>
> +
>
> +                    <div class="social">
>
> +                        <img class="social-icon" src="./assets/facebook (1).svg" alt="">
>
>
> social-icon is an element of social so use social__icon
> ------------------------------
>
> In index.html
> <https://github.com/ishoborabyose/medical-core/pull/1#discussion_r985164250>
> :
>
> > +        <p class="team-paragraph">Problems trying to resolve the conflict between
>
> +            the two major realms of Classical physics: Newtonian mechanics </p>
>
> +
>
> +
>
> +
>
> +            <div class="team-card-container">
>
> +                <div class="team-card">
>
> +                    <img class="team-card__img" src="./assets/image-doctor-3.png" alt="">
>
> +
>
> +                        <p class="team-card__title">Julian Jameson</p>
>
> +                        <p class="team-card__subtitle"> proffession </p>
>
> +
>
> +
>
> +                    <div class="social">
>
> +                        <img class="social-icon" src="./assets/facebook (1).svg" alt="">
>
> +                        <img class="social-icon" src="./assets/instagram (1).svg" alt="">
>
>
> same here
> ------------------------------
>
> In index.html
> <https://github.com/ishoborabyose/medical-core/pull/1#discussion_r985164513>
> :
>
> > @@ -0,0 +1,144 @@
>
> +<!DOCTYPE html>
>
> +<html lang="en">
>
> +<head>
>
> +    <meta charset="UTF-8">
>
> +    <meta http-equiv="X-UA-Compatible" content="IE=edge">
>
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0">
>
> +    <link rel="stylesheet" href="style.css">
>
> +    <title>Medical core</title>
>
> +</head>
>
> +<body>
>
> +    <div class="medical-header__container">
>
>
> medical-header__container is an element without a parent block
> medical-header
> ------------------------------
>
> In index.html
> <https://github.com/ishoborabyose/medical-core/pull/1#discussion_r985164537>
> :
>
> > @@ -0,0 +1,144 @@
>
> +<!DOCTYPE html>
>
> +<html lang="en">
>
> +<head>
>
> +    <meta charset="UTF-8">
>
> +    <meta http-equiv="X-UA-Compatible" content="IE=edge">
>
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0">
>
> +    <link rel="stylesheet" href="style.css">
>
> +    <title>Medical core</title>
>
> +</head>
>
> +<body>
>
> +    <div class="medical-header__container">
>
>
> a block comes before an element
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ishoborabyose/medical-core/pull/1#pullrequestreview-1127580723>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMQCZRY3VKTGW5YZPFWPXELWBDQZ5ANCNFSM6AAAAAAQZSE3BE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-10-02 16:53 UTC, mbukeRepo requested changes
kindly make these simple changes

2022-10-02 16:53 UTC, mbukeRepo commented on index.html
> +        <div class="team-card">
because this card is located in team section use `team__card` instead of `team-card`

2022-10-02 16:53 UTC, mbukeRepo commented on index.html
> +      <h5 class="banner__header">Team</h5>
`banner__header` is an element of `banner` not `team`. use `team__header` in `team` section

2022-10-02 16:53 UTC, mbukeRepo commented on index.html
> +      <div class="team-card-container">
`team-card-container` is not meaning full may be use `team__cards`

2022-10-02 17:30 UTC, ishoborabyose commented
kindly review my code again, thanks.

On Sun, Oct 2, 2022 at 6:53 PM mbuke_repo ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> kindly make these simple changes
> ------------------------------
>
> In index.html
> <https://github.com/ishoborabyose/medical-core/pull/1#discussion_r985266149>
> :
>
> > +          of Classical physics: Newtonian mechanics
> +        </p>
> +        <p class="expert__link">Learn More</p>
> +      </div>
> +    </div>
> +
> +    <div class="team">
> +      <h5 class="banner__header">Team</h5>
> +      <p class="team__moto">Our Team</p>
> +      <p class="team__description">
> +        Problems trying to resolve the conflict between the two major realms of
> +        Classical physics: Newtonian mechanics
> +      </p>
> +
> +      <div class="team-card-container">
> +        <div class="team-card">
>
> because this card is located in team section use team__card instead of
> team-card
> ------------------------------
>
> In index.html
> <https://github.com/ishoborabyose/medical-core/pull/1#discussion_r985266443>
> :
>
> > +    <div class="expert">
> +      <img src="./assets/main-image.png" alt="expert" class="expert__img" />
> +
> +      <div class="expert__body">
> +        <div class="expert__border"></div>
> +        <h2 class="expert__title">Meet Our Experts</h2>
> +        <p class="expert__description">
> +          Problems trying to resolve the conflict between the two major realms
> +          of Classical physics: Newtonian mechanics
> +        </p>
> +        <p class="expert__link">Learn More</p>
> +      </div>
> +    </div>
> +
> +    <div class="team">
> +      <h5 class="banner__header">Team</h5>
>
> banner__header is an element of banner not team. use team__header in team
> section
> ------------------------------
>
> In index.html
> <https://github.com/ishoborabyose/medical-core/pull/1#discussion_r985266567>
> :
>
> > +          Problems trying to resolve the conflict between the two major realms
> +          of Classical physics: Newtonian mechanics
> +        </p>
> +        <p class="expert__link">Learn More</p>
> +      </div>
> +    </div>
> +
> +    <div class="team">
> +      <h5 class="banner__header">Team</h5>
> +      <p class="team__moto">Our Team</p>
> +      <p class="team__description">
> +        Problems trying to resolve the conflict between the two major realms of
> +        Classical physics: Newtonian mechanics
> +      </p>
> +
> +      <div class="team-card-container">
>
> team-card-container is not meaning full may be use team__cards
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ishoborabyose/medical-core/pull/1#pullrequestreview-1127668887>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMQCZR3JVLUHXSPT66RKUGTWBG4XTANCNFSM6AAAAAAQZSE3BE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-10-03 12:43 UTC, mbukeRepo approved these changes
LGTM

2022-10-03 12:43 UTC, mbukeRepo commented on index.html
> +            class="team-card__img"
no parent block called  `team-card` so `team-card__img` is meaningless. Use `team__img` or `team__card__img`

2022-10-03 12:55 UTC, IbrahimBagalwa requested changes
fix this then re-request review

2022-10-03 12:55 UTC, IbrahimBagalwa commented on index.html
> +          <li class="btnn btn--disactive">Learn More</li>
you are using modifier `btn--activee` without its block. or change `btnn` to `btn`

2022-10-03 15:14 UTC, ishoborabyose commented
Updated.

On Mon, Oct 3, 2022 at 2:56 PM Ibrahim Bagalwa ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> fix this then re-request review
> ------------------------------
>
> In index.html
> <https://github.com/ishoborabyose/medical-core/pull/1#discussion_r985747090>
> :
>
> > +        </ul>
> +
> +        <ul class="header__leftbtn">
> +          <li class="btn">Login</li>
> +          <li class="btn btn--active">Join Us</li>
> +        </ul>
> +      </header>
> +
> +      <div class="banner">
> +        <h4 class="banner__header">Welcome</h4>
> +        <p class="banner__description">A Great Place to Receive Care</p>
> +        <p class="banner__moto">Get your best looking smile now!</p>
> +
> +        <ul class="banner__btn">
> +          <li class="btnn btn--activee">Join Us</li>
> +          <li class="btnn btn--disactive">Learn More</li>
>
> you are using modifier btn--activee without its block. or change btnn to
> btn
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ishoborabyose/medical-core/pull/1#pullrequestreview-1128317281>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMQCZR7O4VHTMUGDZB6OZV3WBLJWLANCNFSM6AAAAAAQZSE3BE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-10-03 17:37 UTC, IbrahimBagalwa approved these changes
## Great Job @ishoborabyose 👍 

LGTM 👍  keep it up :)

2022-10-06 11:36 UTC, Morrism1 approved these changes
Good job! 🚀

2022-10-10 05:48 UTC, merged